#!/bin/bash
#
# Remove an entry from the SSH known_hosts file.

KNOWN_HOSTS=$HOME/.ssh/known_hosts

fail() {
    echo "$1"
    exit 1
}

usage() {
    echo "Usage: $(basename $0) IP_ADDR | HOST_NAME"
}

exists () {
    grep -q "$1" $KNOWN_HOSTS
}

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

entry=$1

[[ -w $KNOWN_HOSTS ]] || fail "File $KNOWN_HOSTS does not exist or is not writable"

exists $entry || fail "$entry not found in $KNOWN_HOSTS"

sed -i -e "/$entry/d" $KNOWN_HOSTS

exists $entry && fail "Failed to remove $entry from $KNOWN_HOSTS"

echo "Removed $entry from $KNOWN_HOSTS"
exit 0
