#!/bin/bash
# supdate - update the IP address for the "conductor" host in ssh config
#
# Notes:
#   The number of fields (lines) in the Host entry must match the number of
#   fields printed.  This is not ideal. If you add or subtract config lines 
#   to the "conductor" block, update the first print stmt accordingly.

host=${1:?"specify the SSH host name"}
tag_val=${2:?"specify the instance Name tag value"}

export ipaddr=$(getip $tag_val)
export hostline="Host $host"

cfg=$HOME/.ssh/config

cp $cfg $cfg.bck

awk 'BEGIN {
	FS="\n"
	RS=""
	OFS="\n"
	ORS="\n\n"
}
/Host/ {
	if ($1 == ENVIRON["hostline"]) {
		print $1, "  HostName " ENVIRON["ipaddr"], $3, $4, $5, $6
	} else {
		print $0
	}
}
' $cfg > $cfg.new
[[ $? -ne 0 ]] &&  (echo "failed"; exit 1)
mv $cfg.new $cfg
