#!/bin/bash
# supdate - update the IP address for the "conductor" host in ssh config
#
# Notes:
#   The number of fields (lines) in the Host entry must match the number of
#   fields printed.  This is not ideal. If you add or subtract config lines 
#   to the "conductor" block, update the first print stmt accordingly.

export ipaddr=$(getip "Fugue Conductor")

awk 'BEGIN {
	FS="\n"
	RS=""
	OFS="\n"
	ORS="\n\n"
}
/Host/ {
	if ($1 == "Host conductor") {
		print $1, "  HostName " ENVIRON["ipaddr"], $3, $4, $5, $6
	} else {
		print $0
	}
}
' ~/.ssh/config
